"""Every club's primary colour, and the shade white can be read on.

GENERATED by tools/measure_team_colours.py -- do not hand-edit; re-run it.
Measured 2026-09-08T03:21:56Z from the source the team names themselves come from:

    https://site.api.espn.com/apis/site/v2/sports/<league>/teams?limit=500

Each entry is (primary, on_white, how):

  primary   the club's own colour, used for tints, rules and accents
  on_white  the shade a WHITE name is set on, which is the primary
            when white clears WCAG AA on it, the club's alternate when
            that clears it instead, and the primary darkened until it
            does otherwise
  how       which of those three, so the fallback is a recorded fact
            rather than a runtime guess

NO MARKS. The same payload carries `logos`; a club's logo is its
trademark and none is stored here or anywhere in this package.
"""

MEASURED_UTC = "2026-09-08T03:21:56Z"
SOURCE = "https://site.api.espn.com/apis/site/v2/sports/{path}/teams?limit=500"

TEAM_COLOURS: dict[str, dict[str, tuple[str, str, str]]] = {
  "mlb": {
    "AZ": ("aa182c", "aa182c", "primary"),   # Arizona Diamondbacks
    "ATH": ("003831", "003831", "primary"),   # Athletics
    "ATL": ("0c2340", "0c2340", "primary"),   # Atlanta Braves
    "BAL": ("df4601", "000000", "alternate"),   # Baltimore Orioles
    "BOS": ("0d2b56", "0d2b56", "primary"),   # Boston Red Sox
    "CHC": ("0e3386", "0e3386", "primary"),   # Chicago Cubs
    "CWS": ("000000", "000000", "primary"),   # Chicago White Sox
    "CIN": ("c6011f", "c6011f", "primary"),   # Cincinnati Reds
    "CLE": ("002b5c", "002b5c", "primary"),   # Cleveland Guardians
    "COL": ("33006f", "33006f", "primary"),   # Colorado Rockies
    "DET": ("0a2240", "0a2240", "primary"),   # Detroit Tigers
    "HOU": ("002d62", "002d62", "primary"),   # Houston Astros
    "KC": ("004687", "004687", "primary"),   # Kansas City Royals
    "LAA": ("ba0021", "ba0021", "primary"),   # Los Angeles Angels
    "LAD": ("005a9c", "005a9c", "primary"),   # Los Angeles Dodgers
    "MIA": ("00a3e0", "000000", "alternate"),   # Miami Marlins
    "MIL": ("13294b", "13294b", "primary"),   # Milwaukee Brewers
    "MIN": ("031f40", "031f40", "primary"),   # Minnesota Twins
    "NYM": ("002d72", "002d72", "primary"),   # New York Mets
    "NYY": ("132448", "132448", "primary"),   # New York Yankees
    "PHI": ("e81828", "e81828", "primary"),   # Philadelphia Phillies
    "PIT": ("000000", "000000", "primary"),   # Pittsburgh Pirates
    "SD": ("2f241d", "2f241d", "primary"),   # San Diego Padres
    "SEA": ("005c5c", "005c5c", "primary"),   # Seattle Mariners
    "SF": ("000000", "000000", "primary"),   # San Francisco Giants
    "STL": ("be0a14", "be0a14", "primary"),   # St. Louis Cardinals
    "TB": ("092c5c", "092c5c", "primary"),   # Tampa Bay Rays
    "TEX": ("003278", "003278", "primary"),   # Texas Rangers
    "TOR": ("134a8e", "134a8e", "primary"),   # Toronto Blue Jays
    "WSH": ("ab0003", "ab0003", "primary"),   # Washington Nationals
  },
  "nfl": {
    "ARI": ("a40227", "a40227", "primary"),   # Arizona Cardinals
    "ATL": ("a71930", "a71930", "primary"),   # Atlanta Falcons
    "BAL": ("29126f", "29126f", "primary"),   # Baltimore Ravens
    "BUF": ("00338d", "00338d", "primary"),   # Buffalo Bills
    "CAR": ("0085ca", "000000", "alternate"),   # Carolina Panthers
    "CHI": ("0b1c3a", "0b1c3a", "primary"),   # Chicago Bears
    "CIN": ("fb4f14", "000000", "alternate"),   # Cincinnati Bengals
    "CLE": ("472a08", "472a08", "primary"),   # Cleveland Browns
    "DAL": ("002a5c", "002a5c", "primary"),   # Dallas Cowboys
    "DEN": ("0a2343", "0a2343", "primary"),   # Denver Broncos
    "DET": ("0076b6", "0076b6", "primary"),   # Detroit Lions
    "GB": ("204e32", "204e32", "primary"),   # Green Bay Packers
    "HOU": ("021018", "021018", "primary"),   # Houston Texans
    "IND": ("003b75", "003b75", "primary"),   # Indianapolis Colts
    "JAX": ("007487", "007487", "primary"),   # Jacksonville Jaguars
    "KC": ("e31837", "e31837", "primary"),   # Kansas City Chiefs
    "LAC": ("0080c6", "0073b2", "darkened"),   # Los Angeles Chargers
    "LAR": ("003594", "003594", "primary"),   # Los Angeles Rams
    "LV": ("000000", "000000", "primary"),   # Las Vegas Raiders
    "MIA": ("008e97", "007f87", "darkened"),   # Miami Dolphins
    "MIN": ("4f2683", "4f2683", "primary"),   # Minnesota Vikings
    "NE": ("002a5c", "002a5c", "primary"),   # New England Patriots
    "NO": ("d3bc8d", "000000", "alternate"),   # New Orleans Saints
    "NYG": ("003c7f", "003c7f", "primary"),   # New York Giants
    "NYJ": ("115740", "115740", "primary"),   # New York Jets
    "PHI": ("06424d", "06424d", "primary"),   # Philadelphia Eagles
    "PIT": ("000000", "000000", "primary"),   # Pittsburgh Steelers
    "SEA": ("002a5c", "002a5c", "primary"),   # Seattle Seahawks
    "SF": ("aa0000", "aa0000", "primary"),   # San Francisco 49ers
    "TB": ("bd1c36", "bd1c36", "primary"),   # Tampa Bay Buccaneers
    "TEN": ("4495d2", "001532", "alternate"),   # Tennessee Titans
    "WSH": ("5a1414", "5a1414", "primary"),   # Washington Commanders
  },
  "nba": {
    "ATL": ("c8102e", "c8102e", "primary"),   # Atlanta Hawks
    "BKN": ("000000", "000000", "primary"),   # Brooklyn Nets
    "BOS": ("008348", "008348", "primary"),   # Boston Celtics
    "CHA": ("008ca8", "1d1060", "alternate"),   # Charlotte Hornets
    "CHI": ("ce1141", "ce1141", "primary"),   # Chicago Bulls
    "CLE": ("860038", "860038", "primary"),   # Cleveland Cavaliers
    "DAL": ("0064b1", "0064b1", "primary"),   # Dallas Mavericks
    "DEN": ("0e2240", "0e2240", "primary"),   # Denver Nuggets
    "DET": ("1d428a", "1d428a", "primary"),   # Detroit Pistons
    "GSW": ("fdb927", "1d428a", "alternate"),   # Golden State Warriors
    "HOU": ("ce0e2d", "ce0e2d", "primary"),   # Houston Rockets
    "IND": ("0c2340", "0c2340", "primary"),   # Indiana Pacers
    "LAC": ("12173f", "12173f", "primary"),   # LA Clippers
    "LAL": ("552583", "552583", "primary"),   # Los Angeles Lakers
    "MEM": ("5d76a9", "5d76a9", "primary"),   # Memphis Grizzlies
    "MIA": ("98002e", "98002e", "primary"),   # Miami Heat
    "MIL": ("00471b", "00471b", "primary"),   # Milwaukee Bucks
    "MIN": ("266092", "266092", "primary"),   # Minnesota Timberwolves
    "NOP": ("0a2240", "0a2240", "primary"),   # New Orleans Pelicans
    "NYK": ("1d428a", "1d428a", "primary"),   # New York Knicks
    "OKC": ("007ac1", "007ac1", "primary"),   # Oklahoma City Thunder
    "ORL": ("0150b5", "0150b5", "primary"),   # Orlando Magic
    "PHI": ("1d428a", "1d428a", "primary"),   # Philadelphia 76ers
    "PHX": ("29127a", "29127a", "primary"),   # Phoenix Suns
    "POR": ("e03a3e", "000000", "alternate"),   # Portland Trail Blazers
    "SAS": ("000000", "000000", "primary"),   # San Antonio Spurs
    "SAC": ("5a2d81", "5a2d81", "primary"),   # Sacramento Kings
    "TOR": ("d91244", "d91244", "primary"),   # Toronto Raptors
    "UTA": ("4e008e", "4e008e", "primary"),   # Utah Jazz
    "WAS": ("e31837", "e31837", "primary"),   # Washington Wizards
  },
  "cfb": {
    "AAMU": ("790000", "790000", "primary"),   # Alabama A&M Bulldogs
    "ACU": ("592d82", "592d82", "primary"),   # Abilene Christian Wildcats
    "AKR": ("041e42", "041e42", "primary"),   # Akron Zips
    "ALA": ("9e1b32", "9e1b32", "primary"),   # Alabama Crimson Tide
    "ALCN": ("4b0058", "4b0058", "primary"),   # Alcorn State Braves
    "ALST": ("e9a900", "0a0a0a", "alternate"),   # Alabama State Hornets
    "APP": ("000000", "000000", "primary"),   # App State Mountaineers
    "APSU": ("8e0b0b", "8e0b0b", "primary"),   # Austin Peay Governors
    "ARIZ": ("cc0033", "cc0033", "primary"),   # Arizona Wildcats
    "ARK": ("a32136", "a32136", "primary"),   # Arkansas Razorbacks
    "ARMY": ("000000", "000000", "primary"),   # Army Black Knights
    "ARST": ("cc092f", "cc092f", "primary"),   # Arkansas State Red Wolves
    "ASU": ("ffc627", "8c1d40", "alternate"),   # Arizona State Sun Devils
    "AUB": ("002b5c", "002b5c", "primary"),   # Auburn Tigers
    "BALL": ("ba0c2f", "ba0c2f", "primary"),   # Ball State Cardinals
    "BAY": ("154734", "154734", "primary"),   # Baylor Bears
    "BC": ("8c2232", "8c2232", "primary"),   # Boston College Eagles
    "BCU": ("7b1831", "7b1831", "primary"),   # Bethune-Cookman Wildcats
    "BGSU": ("fd5000", "4f2c1d", "alternate"),   # Bowling Green Falcons
    "BOIS": ("0033a0", "0033a0", "primary"),   # Boise State Broncos
    "BUCK": ("000060", "000060", "primary"),   # Bucknell Bison
    "BYU": ("0047ba", "0047ba", "primary"),   # BYU Cougars
    "CAL": ("041e42", "041e42", "primary"),   # California Golden Bears
    "CAM": ("000000", "000000", "primary"),   # Campbell Fighting Camels
    "CARK": ("a7a9ac", "6c6d6f", "darkened"),   # Central Arkansas Bears
    "CCSU": ("1b49a2", "1b49a2", "primary"),   # Central Connecticut Blue Devils
    "CCU": ("006f71", "006f71", "primary"),   # Coastal Carolina Chanticleers
    "CHSO": ("2e3192", "2e3192", "primary"),   # Charleston Southern Buccaneers
    "CIN": ("000000", "000000", "primary"),   # Cincinnati Bearcats
    "CLEM": ("f56600", "c65100", "darkened"),   # Clemson Tigers
    "CLT": ("005035", "005035", "primary"),   # Charlotte 49ers
    "CMU": ("4c0027", "4c0027", "primary"),   # Central Michigan Chippewas
    "COLG": ("821019", "821019", "primary"),   # Colgate Raiders
    "COLO": ("cfb87c", "000000", "alternate"),   # Colorado Buffaloes
    "CONN": ("0c2340", "0c2340", "primary"),   # UConn Huskies
    "CP": ("1e4d2b", "1e4d2b", "primary"),   # Cal Poly Mustangs
    "CSU": ("004c23", "004c23", "primary"),   # Colorado State Rams
    "DEL": ("00539f", "00539f", "primary"),   # Delaware Blue Hens
    "DSU": ("009cdb", "d51c28", "alternate"),   # Delaware State Hornets
    "DUKE": ("00539b", "00539b", "primary"),   # Duke Blue Devils
    "DUQ": ("002d62", "002d62", "primary"),   # Duquesne Dukes
    "ECU": ("582c83", "582c83", "primary"),   # East Carolina Pirates
    "EIU": ("000000", "000000", "primary"),   # Eastern Illinois Panthers
    "EKU": ("660819", "660819", "primary"),   # Eastern Kentucky Colonels
    "ELON": ("020303", "020303", "primary"),   # Elon Phoenix
    "EMU": ("006938", "006938", "primary"),   # Eastern Michigan Eagles
    "ETSU": ("002d61", "002d61", "primary"),   # East Tennessee State Buccaneers
    "EWU": ("a10022", "a10022", "primary"),   # Eastern Washington Eagles
    "FAMU": ("f89728", "00843d", "alternate"),   # Florida A&M Rattlers
    "FAU": ("003366", "003366", "primary"),   # Florida Atlantic Owls
    "FIU": ("091f3f", "091f3f", "primary"),   # Florida International Panthers
    "FLA": ("0021a5", "0021a5", "primary"),   # Florida Gators
    "FOR": ("830032", "830032", "primary"),   # Fordham Rams
    "FRES": ("b1102b", "b1102b", "primary"),   # Fresno State Bulldogs
    "FSU": ("782f40", "782f40", "primary"),   # Florida State Seminoles
    "FUR": ("582c83", "582c83", "primary"),   # Furman Paladins
    "GASO": ("041e42", "041e42", "primary"),   # Georgia Southern Eagles
    "GAST": ("0039a6", "0039a6", "primary"),   # Georgia State Panthers
    "GT": ("b3a369", "81754b", "darkened"),   # Georgia Tech Yellow Jackets
    "GWEB": ("c12535", "c12535", "primary"),   # Gardner-Webb Runnin' Bulldogs
    "HAMP": ("0067ac", "0067ac", "primary"),   # Hampton Pirates
    "HAW": ("005737", "005737", "primary"),   # Hawai'i Rainbow Warriors
    "HC": ("582c83", "582c83", "primary"),   # Holy Cross Crusaders
    "HCU": ("00539c", "00539c", "primary"),   # Houston Christian Huskies
    "HOU": ("c8102e", "c8102e", "primary"),   # Houston Cougars
    "HOW": ("003a63", "003a63", "primary"),   # Howard Bison
    "IDHO": ("000000", "000000", "primary"),   # Idaho Vandals
    "IDST": ("ef8c00", "ad6500", "darkened"),   # Idaho State Bengals
    "ILL": ("ff5f05", "13294b", "alternate"),   # Illinois Fighting Illini
    "ILST": ("ce1126", "ce1126", "primary"),   # Illinois State Redbirds
    "INST": ("00669a", "00669a", "primary"),   # Indiana State Sycamores
    "IOWA": ("231f20", "231f20", "primary"),   # Iowa Hawkeyes
    "ISU": ("ae192d", "ae192d", "primary"),   # Iowa State Cyclones
    "IU": ("970310", "970310", "primary"),   # Indiana Hoosiers
    "JKST": ("123297", "123297", "primary"),   # Jackson State Tigers
    "JMU": ("450084", "450084", "primary"),   # James Madison Dukes
    "KENN": ("fdbb30", "0b1315", "alternate"),   # Kennesaw State Owls
    "KENT": ("002664", "002664", "primary"),   # Kent State Golden Flashes
    "KSU": ("330a57", "330a57", "primary"),   # Kansas State Wildcats
    "KU": ("0051ba", "0051ba", "primary"),   # Kansas Jayhawks
    "LAF": ("790000", "790000", "primary"),   # Lafayette Leopards
    "LAM": ("000000", "000000", "primary"),   # Lamar Cardinals
    "LEH": ("6c2b2a", "6c2b2a", "primary"),   # Lehigh Mountain Hawks
    "LIB": ("0a254e", "0a254e", "primary"),   # Liberty Flames
    "LOU": ("c9001f", "c9001f", "primary"),   # Louisville Cardinals
    "LSU": ("461d76", "461d76", "primary"),   # LSU Tigers
    "LT": ("003087", "003087", "primary"),   # Louisiana Tech Bulldogs
    "M-OH": ("c41230", "c41230", "primary"),   # Miami (OH) RedHawks
    "MASS": ("881c1c", "881c1c", "primary"),   # Massachusetts Minutemen
    "MCN": ("00529c", "00529c", "primary"),   # McNeese Cowboys
    "MD": ("ce1126", "ce1126", "primary"),   # Maryland Terrapins
    "ME": ("127dbe", "1070ab", "darkened"),   # Maine Black Bears
    "MEM": ("004991", "004991", "primary"),   # Memphis Tigers
    "MER": ("ff7f29", "080808", "alternate"),   # Mercer Bears
    "MERC": ("000000", "000000", "primary"),   # Mercyhurst Lakers
    "MIA": ("f47423", "035131", "alternate"),   # Miami Hurricanes
    "MICH": ("00274c", "00274c", "primary"),   # Michigan Wolverines
    "MINN": ("5e0a2f", "5e0a2f", "primary"),   # Minnesota Golden Gophers
    "MISS": ("13294b", "13294b", "primary"),   # Ole Miss Rebels
    "MIZ": ("f1b82d", "000000", "alternate"),   # Missouri Tigers
    "MONM": ("051844", "051844", "primary"),   # Monmouth Hawks
    "MONT": ("751d4a", "751d4a", "primary"),   # Montana Grizzlies
    "MORG": ("014786", "014786", "primary"),   # Morgan State Bears
    "MRSH": ("00b140", "000000", "alternate"),   # Marshall Thundering Herd
    "MSST": ("5d1725", "5d1725", "primary"),   # Mississippi State Bulldogs
    "MSU": ("173f35", "173f35", "primary"),   # Michigan State Spartans
    "MTST": ("00205c", "00205c", "primary"),   # Montana State Bobcats
    "MTSU": ("036eb7", "036eb7", "primary"),   # Middle Tennessee Blue Raiders
    "MUR": ("002148", "002148", "primary"),   # Murray State Racers
    "MVSU": ("005328", "005328", "primary"),   # Mississippi Valley State Delta Devils
    "NAU": ("003976", "003976", "primary"),   # Northern Arizona Lumberjacks
    "NAVY": ("00225b", "00225b", "primary"),   # Navy Midshipmen
    "NCAT": ("0505aa", "0505aa", "primary"),   # North Carolina A&T Aggies
    "NCCU": ("880023", "880023", "primary"),   # North Carolina Central Eagles
    "NCSU": ("cc0000", "cc0000", "primary"),   # NC State Wolfpack
    "ND": ("062340", "062340", "primary"),   # Notre Dame Fighting Irish
    "NDSU": ("01402a", "01402a", "primary"),   # North Dakota State Bison
    "NEB": ("e31937", "e31937", "primary"),   # Nebraska Cornhuskers
    "NEV": ("041e42", "041e42", "primary"),   # Nevada Wolf Pack
    "NICH": ("c41230", "c41230", "primary"),   # Nicholls Colonels
    "NIU": ("c8102e", "c8102e", "primary"),   # Northern Illinois Huskies
    "NMSU": ("7e141b", "7e141b", "primary"),   # New Mexico State Aggies
    "NORF": ("0c8968", "0a7b5d", "darkened"),   # Norfolk State Spartans
    "NU": ("492f92", "492f92", "primary"),   # Northwestern Wildcats
    "NWST": ("492f91", "492f91", "primary"),   # Northwestern State Demons
    "ODU": ("003768", "003768", "primary"),   # Old Dominion Monarchs
    "OHIO": ("154734", "154734", "primary"),   # Ohio Bobcats
    "OKST": ("fe5c00", "000000", "alternate"),   # Oklahoma State Cowboys
    "ORE": ("00934b", "008443", "darkened"),   # Oregon Ducks
    "ORST": ("dc4405", "000000", "alternate"),   # Oregon State Beavers
    "OSU": ("ba0c2f", "ba0c2f", "primary"),   # Ohio State Buckeyes
    "OU": ("990000", "990000", "primary"),   # Oklahoma Sooners
    "PITT": ("003594", "003594", "primary"),   # Pittsburgh Panthers
    "PRST": ("00311e", "00311e", "primary"),   # Portland State Vikings
    "PSU": ("061440", "061440", "primary"),   # Penn State Nittany Lions
    "PV": ("582c83", "582c83", "primary"),   # Prairie View A&M Panthers
    "RICE": ("00205b", "00205b", "primary"),   # Rice Owls
    "RICH": ("9e0712", "9e0712", "primary"),   # Richmond Spiders
    "RUTG": ("ce0e2d", "ce0e2d", "primary"),   # Rutgers Scarlet Knights
    "SAC": ("00573c", "00573c", "primary"),   # Sacramento State Hornets
    "SDAK": ("cd1241", "cd1241", "primary"),   # South Dakota Coyotes
    "SDSU": ("a6192e", "a6192e", "primary"),   # San Diego State Aztecs
    "SIU": ("85283d", "85283d", "primary"),   # Southern Illinois Salukis
    "SJSU": ("0038a8", "0038a8", "primary"),   # San José State Spartans
    "STAN": ("8c1515", "8c1515", "primary"),   # Stanford Cardinal
    "STO": ("000000", "000000", "primary"),   # Stonehill Skyhawks
    "SUU": ("c72026", "c72026", "primary"),   # Southern Utah Thunderbirds
    "SYR": ("000e54", "000e54", "primary"),   # Syracuse Orange
    "TA&M": ("500000", "500000", "primary"),   # Texas A&M Aggies
    "TEM": ("a41e35", "a41e35", "primary"),   # Temple Owls
    "TEX": ("af5c37", "af5c37", "primary"),   # Texas Longhorns
    "TLSA": ("003595", "003595", "primary"),   # Tulsa Golden Hurricane
    "TOW": ("ffc229", "957116", "darkened"),   # Towson Tigers
    "TXST": ("501214", "501214", "primary"),   # Texas State Bobcats
    "UAB": ("1a5632", "1a5632", "primary"),   # UAB Blazers
    "UAPB": ("e0aa0f", "916e08", "darkened"),   # Arkansas-Pine Bluff Golden Lions
    "UCD": ("002855", "002855", "primary"),   # UC Davis Aggies
    "UCF": ("000000", "000000", "primary"),   # UCF Knights
    "UCLA": ("2774ae", "2774ae", "primary"),   # UCLA Bruins
    "UGA": ("ba0c2f", "ba0c2f", "primary"),   # Georgia Bulldogs
    "UK": ("0033a0", "0033a0", "primary"),   # Kentucky Wildcats
    "UL": ("ce181e", "ce181e", "primary"),   # Louisiana Ragin' Cajuns
    "ULM": ("840029", "840029", "primary"),   # UL Monroe Warhawks
    "UNA": ("000000", "000000", "primary"),   # North Alabama Lions
    "UNC": ("7bafd4", "13294b", "alternate"),   # North Carolina Tar Heels
    "UNCO": ("13558d", "13558d", "primary"),   # Northern Colorado Bears
    "UND": ("00a26b", "008256", "darkened"),   # North Dakota Fighting Hawks
    "UNH": ("004990", "004990", "primary"),   # New Hampshire Wildcats
    "UNI": ("473282", "473282", "primary"),   # Northern Iowa Panthers
    "UNLV": ("cf0a2c", "cf0a2c", "primary"),   # UNLV Rebels
    "UNM": ("ba0c2f", "ba0c2f", "primary"),   # New Mexico Lobos
    "UNT": ("068f33", "05802d", "darkened"),   # North Texas Mean Green
    "URI": ("091f3f", "091f3f", "primary"),   # Rhode Island Rams
    "USA": ("00205b", "00205b", "primary"),   # South Alabama Jaguars
    "USC": ("9d2235", "9d2235", "primary"),   # USC Trojans
    "USF": ("006747", "006747", "primary"),   # South Florida Bulls
    "USU": ("0f2439", "0f2439", "primary"),   # Utah State Aggies
    "UTAH": ("be0000", "be0000", "primary"),   # Utah Utes
    "UTC": ("00386b", "00386b", "primary"),   # Chattanooga Mocs
    "UVA": ("232d4b", "232d4b", "primary"),   # Virginia Cavaliers
    "VAN": ("000000", "000000", "primary"),   # Vanderbilt Commodores
    "VILL": ("00205b", "00205b", "primary"),   # Villanova Wildcats
    "VT": ("6a2c3e", "6a2c3e", "primary"),   # Virginia Tech Hokies
    "WAKE": ("ceb888", "2c2a29", "alternate"),   # Wake Forest Demon Deacons
    "WASH": ("33006f", "33006f", "primary"),   # Washington Huskies
    "WIS": ("a00000", "a00000", "primary"),   # Wisconsin Badgers
    "WKU": ("e13a3e", "ca3437", "darkened"),   # Western Kentucky Hilltoppers
    "WSU": ("a60f2d", "a60f2d", "primary"),   # Washington State Cougars
    "WVU": ("eaaa00", "002855", "alternate"),   # West Virginia Mountaineers
  },
}
